<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net472;net8.0;net9.0;net10.0;net11.0</TargetFrameworks>
    <RepositoryType>git</RepositoryType>
    <Version>100.100.100</Version>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release;TestWindows</Configurations>
    <Platforms>AnyCPU</Platforms>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <PropertyGroup Condition="  '$(TargetFramework)' == 'net472' ">
    <LangVersion>12.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="McMaster.Extensions.CommandLineUtils" />
    <PackageReference Include="TestableIO.System.IO.Abstractions.Wrappers" />
    <PackageReference Include="TestableIO.System.IO.Abstractions.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup Condition="  '$(TargetFramework)' == 'net8.0' ">
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net472'">
    <PackageReference Include="System.Text.Json" />
    <PackageReference Include="System.IO.Hashing" />
    <PackageReference Include="System.Collections.Immutable" />
    <PackageReference Include="PolySharp">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FileLicenseMatcher\FileLicenseMatcher.csproj" />
    <ProjectReference Include="..\NuGetUtility\NuGetUtility.csproj" />
  </ItemGroup>
</Project>